### ISSUE TITLE
How to install and configure matomo On-premise?

### ISSUE THREAD

**Issue by spanjaan** [wintercms/wn-matomo-plugin#11]
Hello,

i am new in wintercms. i don't have any idea how to install and configure matomo On-premise method.
Please help me.

Thank You.

**Comment by bennothommo** [comment]
Sorry, we can't offer support for a third-party product. All their documentation for on-premise installation is here:
https://matomo.org/guide/installation-maintenance/matomo-on-premise-self-hosted/

**Comment by bennothommo** [comment]
Are you asking for help with installing this plugin for an on-premise installation? Or are you asking for help to install Matomo on-premise itself?

**Comment by spanjaan** [comment]
i am asking for help with installing this plugin for an on-premise installation.

**Comment by LukeTowers** [comment]
@spanjaan this plugin has a [configuration file](https://github.com/wintercms/wn-matomo-plugin/blob/main/config/config.php) with support for loading from environment variables (or the `.env` file). If you are currently using a `.env` file, then simply add the following to it:

```.env
MATOMO_SERVER=https://matomo.example.com/
MATOMO_SITE_ID=1
MATOMO_TOKEN=myTokenHere
```

If you are not, then just copy `myproject/plugins/winter/matomo/config/config.php` to `myproject/config/winter/matomo/config.php` and make the changes there.

**Comment by spanjaan** [comment]
@LukeTowers how to find MATOMO_SERVER, MATOMO_TOKEN?
i need to configure Self-host Matomo Analytics method.
Please help me.

**Comment by LukeTowers** [comment]
Follow matomos documentation and instructions. Server url is the url to your matomo install and the token you create as part of the setup process. You only need it if you want to use the reporting functionality in this plugin though, if you only need to setup the tracking script then just the url and site id are all that you need.
